name: Docker Image CI

on:
  push:
    branches: [ "prod" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Publish Docker Image
      run: |
        docker build -t arnabdaz/dcc_21_days_dev:latest .
        docker push arnabdaz/dcc_21_days_dev:latest

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd ~/dcc_21_days_dev
          docker-compose pull nodeapp
          docker-compose up -d --no-deps --build nodeapp
